### PR TITLE
Feature/split fandiscs to main chart

### PR DESCRIPTION
**Pull request by Pinkfag**
New feature for adding fandiscs to the main chart

Changes:
- Updated filter for picking VNs that have sequels
- New filter to hide VNs that ARE sequels
- New stacking UI when hiding sequels
- New scenario selection filter
- Colour coded icon bar to increase genre readability
- Name no longer takes you to vndb link (Due to adding new clickable nearby and not wanting accidental link clicks)
- When hiding sequels, a help Icon appears next to the title name. Clicking on it will display all the translated FDs/Sequels for that given VN
- When sorting by chronological, the translation release date is now displayed.

Screenshots:

Default view
image

Display sequels
image

Both sequel filters enabled (Note: stack effect does not occur)
image

Upcoming section
image

Clicking on the help icon in the title when hiding sequels
image

Chronological sort
image

### CODE REVIEW

**Comment by Pinkfag** [comment]
@chartanon let's have any further discussions on the FD branch in here, rather than the requests thread

**Comment by Pinkfag** [comment]
>Everything should be on the chart now. I combined some series like Majikoi A-1-A4 or the Whirpool games into a single entry to get rid of the worst bloat. I'll probably do the same with all the qureate shovelware that's polluting the chart, but not right now.

Honestly I don't know if this is the best solution. Combining all the FDs for a series into one entry doesn't seem great in scenarios where one FD might have a substantial enough narrative/theme shift compared to others.

Also you'd have to edit the thumbnail for the relevant series FD entry whenever a new one comes out, which just makes the thumbnail busier the more entries there are. (There is also the low chance for error where you accidentally add an FD as a new entry, rather than updating an existing FD collection entry, if you forgot that a VN already had one)

>Oh and I noticed that a lot of FDs have scenario/heroine selection. I was thinking about adding an icon for that down the line. I only marked them with comments for now and left it as branching plot.
Also I only commented the old HAS_SEQUELS attribute out in case we want to reintroduce it. Maybe only show it if the FDs are hidden or something? It would need a different icon though. It's just an idea, I'm not against removing it completely

Scenario/heroine selection as a new filter sounds good, no issues there.

Regarding FDs, I think I may have a good long term solution. How about we:
1. Tag all base games as "has Sequels" (eg: Aokana)
2. Tag all FDs/Sequels as "is Sequel" (eg: Aokana Extra 1)

This way we can have:
1. A filter to show games that have sequels (and probably the sequels themselves)
2. A filter to hide sequels themselves (A filter to only show sequels doesn't sound as helpful)

I think with those tags, the main chart will already be really good (we can default the hide sequels filter to be on) and also make it very straightforward to add new FDs.

I think if we want to do even more, there's the option of creating a new `Series` enum, which will be a new optional field on VNs. That way we can group base games and their FDs together.
I can then use that to, for example:
1.  Have it where you click on a VN, and it'll display all of it's FDs in a new UI component (Maybe it blurs the site and displays the FDs on top)
2. Add a new icon on the VN cards where clicking on it filters out all VNs that aren't part of that VN's series.

What're your thoughts @chartanon? Let me know if anything I mentioned sounds confusing and I can try to explain it better.

**Comment by Pinkfag** [comment]
Also from here on out, please update the `Last Updated` field in `src\views\HomePage\Chart\MoegeChart.tsx` whenever you add new VNs to the chart.

**Comment by chartanon** [comment]
> Honestly I don't know if this is the best solution. Combining all the FDs for a series into one entry doesn't seem great in scenarios where one FD might have a substantial enough narrative/theme shift compared to others.

It's not a great solution, that's true. I just got annoyed by some series with an excessive amount of entries. Neko-nin would have 6 entries for something really minor. Add the other whirlpool VNs and a big chunk of the chart is flodded with them. I know it's not a problem if FD are filtered, but turn the filter off and the chart will eventually become a mess.

> I think if we want to do even more, there's the option of creating a new `Series` enum, which will be a new optional field on VNs. That way we can group base games and their FDs together. I can then use that to, for example:
> 
> 1. Have it where you click on a VN, and it'll display all of it's FDs in a new UI component (Maybe it blurs the site and displays the FDs on top)

This probably scales the best in the long run. It solves all the other problematic cases as well while keeping things organized.
We cannot only group base VN and FDs/sequels but also series that are more loosely connected like Loca Love or all the qureate VNs (NinNinDays, TroubleDays, etc.). 

The question is how sorting by newest releases should work. In my opinion every VN (even FDs) should be shown as its own entry if you sort by newest releases.
Alternatively sort by the latest release date in the series and keep the entries grouped together.

I'm not sure if this is overkill though. We could just go with
> 1. Tag all base games as "has Sequels" (eg: Aokana)
> 2. Tag all FDs/Sequels as "is Sequel" (eg: Aokana Extra 1)

And I add all the other VNs I grouped for now.

It's your decision. If we do the grouping I'll do the data work

**Comment by Pinkfag** [comment]
I'm fine with doing both, as in we tag base games as `has Sequels` and `is Sequel` for FDs/Sequel games (including stuff like Loca Love 2/3). And then also adding a `Series` enum, such as `Series.AOKANA` and `SERIES.NIN_NIN_DAYS`. This gives me the most freedom to code whatever solution I want, and makes stuff the most maintainable for you as well in the future (adding new `Series` will be very easy, I'll add one right now for you to see as an example).

**Comment by Pinkfag** [comment]
>I know it's not a problem if FD are filtered, but turn the filter off and the chart will eventually become a mess.

I still think this is fine. Again, we can default FD filter to being enabled. The reason why I think this is best is because of scenarios such as:
1. Moege FD 2 and 3 comes out at relatively close times
2. User filters by newest releases
3. User only sees FD 3 and not FD 2 (unless they click to expand, or whatever)

I suppose we could add a disclaimer somewhere on the VN card to notify which VNs in a series have come out recently, but I'd prefer to not too much stuff to the cards for readability's sake.

>The question is how sorting by newest releases should work. In my opinion every VN (even FDs) should be shown as its own entry if you sort by newest releases.

The UI experience might be weird if FDs are originally always hidden behind the base game, but then they're suddenly revealed when sorting by newest releases. I think for FDs we should always have them hidden, or always have them displayed on the main chart.

**Comment by Pinkfag** [comment]
Okay, I'm proposing this:

1. You add the `isSequel`, `hasSequels` and `Series` fields to the relevant VNs now (Also I guess if we want a new icon so we have one for isSequel and hasSequel, make one and post it here)
2. I'll add the filters to show/hide sequels
3. Merge that
4. I'll work on having the FDs stack/group on the base game as follow-up, or if we're happy with the first set of changes we can stop here

**Comment by Pinkfag** [comment]
>We cannot only group base VN and FDs/sequels but also series that are more loosely connected like Loca Love or all the qureate VNs (NinNinDays, TroubleDays, etc.).

Actually, can you elaborate what you mean by this? Why can't we just group only series together?

**Comment by Pinkfag** [comment]
If there's really a need for it, we can also add a new field for VN developer, if we want to group by that criteria as well. Though I don't know if we need that right now

**Comment by Pinkfag** [comment]
Also I haven't read it yet, but would kimaten be considered a moe/moenukige?

**Comment by Pinkfag** [comment]
Think I have a good finalized solution:

- We have a `Has sequels` filter
- We have a `Hide sequels` filter
  - When it's disabled, all VNs, FD or otherwise, are displayed as their own entry
  - When it's enabled, hide all FDs in a stack behind the base game (You can see them by clicking a show more button)
- Sorting by chronological will now update the title to include the translation date. (So Aokana -> Aokana (2023-09-27))
  - If `HIDE SEQUELS=TRUE`, the title will change to the latest FD's translation date. (Aokana -> Aokana Extra 2 - (2022-12-16))

There is still the minor issue that if you choose to hide the sequels and sort chronologically, you'll only know about the latest entry with this solution, however in this scenario the user explicitly chose to hide sequels, so odds are they're not going to be bothered by it.

**Comment by Pinkfag** [comment]
For the icons, I'm thinking we have the `Has Sequels` be a disc with a 2nd one stacked behind it. `Is Sequel` could just be a singular disc maybe? I dunno, what're your thoughts regarding that?

**Comment by Pinkfag** [comment]
I've updated to VN FD fields, base games now have an array of sequels (vndb links). Sequels themselves will now have an originalGame field that should contain a vndb link as well. Please take a look at how I've done it for Aokana, and propagate that change to the rest of the VNs with sequels/are sequels (maybe while you're splitting drapri/majikoi/whatever else into 1 entry per game too)

**Comment by Pinkfag** [comment]
There's a bunch of stuff we both need to do, so I'm adding them as TODOs to the original comment of this PR. Let me know if there's anything missing

**Comment by chartanon** [comment]
So I went ahead and checked these off
- Update sequels and originalGame fields for relevant VNs
- Split up any FD VNs that were combined, into their own solo entries
- Update last updated field when finished with data entry work

Still to do:
- Create new icons for base games and FDs?

> For the icons, I'm thinking we have the Has Sequels be a disc with a 2nd one stacked behind it. Is Sequel could just be a singular disc maybe? I dunno, what're your thoughts regarding that?

We can do that or we use the old FD icon for Has Sequels and just a disc for Is Sequel


> Actually, can you elaborate what you mean by this? Why can't we just group only series together?

Looks like I was a bit tired yesterday. I wanted to say that we should group series that aren't direct sequels/prequels of eachother like Loca Love, Uchi no Koibito/Kanojo, etc.

> If there's really a need for it, we can also add a new field for VN developer

I don't think we need that tbh. Vndb still exists

> Also I haven't read it yet, but would kimaten be considered a moe/moenukige?

It's not a moege

**Comment by Pinkfag** [comment]
>We can do that or we use the old FD icon for Has Sequels and just a disc for Is Sequel

Yeah that sounds fine

>Looks like I was a bit tired yesterday. I wanted to say that we should group series that aren't direct sequels/prequels of eachother like Loca Love, Uchi no Koibito/Kanojo, etc.

>I don't think we need that tbh. Vndb still exists

Ryoukai

>It's not a moege

It's not? That's disappointing

**Comment by Pinkfag** [comment]
image
Any reason why we have the playtime length on these entries in the upcoming section?

**Comment by chartanon** [comment]
You didn't see anything.

Anyway, here are some icons. I changed the disc icon a bit 
Has sequel icon-has-sequel
Is sequel icon-sequel
Scenario selection icon-selection

**Comment by Pinkfag** [comment]
Alright quick question, do we want to icons on the side to be a fixed distance from the original game's card, or do we want the margin to increase as there are more entries? 
Scaling example:
image

Fixed example:
image

**Comment by Pinkfag** [comment]
I can tweak the background opacity for the icons so that they'll always be readable for the fixed example

image

**Comment by Pinkfag** [comment]
Never mind, I'm going to do fixed. There's an issue when you enable both isSequel and hasSequel filters, the extra cards don't appear but the scaling margin still triggers. I don't really want to deal with fixing that, so fixed it is.

**Comment by Pinkfag** [comment]
Pushed my current set of changes, and added the new scenario selection attribute. Feel free to add them for the rest (tested with konosora FD to confirm it works)

**Comment by Pinkfag** [comment]
Decided to not have VNDB cards display the translation date of the newest FD in the title, because it doesn't really make sense for someone using the chart who has `hide sequels` on who would want their chronological sort to display FD releases.

**Comment by Pinkfag** [comment]
Merging this PR, will move the scenario selection data entry todo into the next branch (recommended VNs)

**Pull request merged**
