### PR TITLE
feature/migrate-to-react-with-dummy-data

### PR DESCRIPTION
**Pull request by Pinkfag**
I've migrated the moechart to react, however I haven't fully populated the chart with all the VN data yet.
I'm hoping you might be able to help me with that, and I can also teach you how to deploy the react-app, since the steps are a bit different than with just HTML and CSS (but still very easy)
Once this gets merged, I'll begin working on adding additional functionality to the chart.

Screenshots:
image

### CODE REVIEW

**Comment by Pinkfag** [comment]
@chartanon thanks for adding me as collaborator! Though like I said in the PR, I don't want to merge this until we talk about how the website will work now/how to add new entries to the site

**Comment by chartanon** [comment]
Looks good. I want the old site to stay up until the react port is functional so I'll go ahead and merge this to a new branch and start working on the data migration.

**Comment by Pinkfag** [comment]
Thanks a bunch! I'm still at work so responses won't be very quick, but let me know if you have any questions.
Also if you could, please fill out the `translationReleaseDate` fields for all the released VNs in addition to migrating the existing stuff over (use the same format I have in the examples, with `Date.parse`).
There's also the `isUpcomingRelease` field that should be set to `true` for upcoming releases.
I'm going to be using these for future functions.

**Comment by Pinkfag** [comment]
Also if there are new fields we should be accounting for, let me know and I can add them. (For example, if we want to add a pinkHair boolean to filter/sort vns by)

**Comment by Pinkfag** [comment]
Finally, here are some useful links you'll need for deploying a react-app to github. We can go through this stuff together if you'd like
https://code.visualstudio.com
https://www.youtube.com/watch?v=HWpjpq2ux04
https://www.youtube.com/watch?v=4G6O0BIoq6M

**Comment by chartanon** [comment]
Okay, I added the VN data. There are still some things that need to be done:
1. The release dates for upcoming VN are still dummies. Should we remove them completely or use them to store future dates if available?
2. The playtime icons, etc. for upcoming VNs are also dummies since the original chart didn't use them. Keep of remove?

**Comment by Pinkfag** [comment]
1. If you are talking about `translationReleaseDate`, that field was intentionally made optional. You can remove that line from objects in `visualNovelData` and it won't throw any errors.
2. If you're talking about the `attributes` field, you can set it to an empty array. eg: `attributes: []` if you don't want them to have any icons.

**Pull request merged**
